name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Cache Flutter
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{runner.os}}-flutter
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Build widgetbook
        run: flutter build web --dart-define=widgetbook=true --release --web-renderer html --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAKBAY_F1B2E }}'
          projectId: lakbay-f1b2e
          expires: 3d 
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels